spring:
  datasource:
    testWhileIdle: true
    validationQuery: SELECT 1
  cache:
    type: NONE
# JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect

# Eureka
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://127.0.0.1:8099/eureka}
    fetch-registry: true
  instance:
    preferIpAddress: true
    hostname: 127.0.0.1

# Logging
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
  file: /logs/app.log

# DB Pool
bonecp:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://192.168.1.12:5432/sharincraftsmanlibrary
  username: docker
  password: docker
  idleMaxAgeInMinutes: 240
  idleConnectionTestPeriodInMinutes: 60
  maxConnectionsPerPartition: 10
  minConnectionsPerPartition: 1
  partitionCount: 2
  acquireIncrement: 5
  statementsCacheSize: 100

# CQRS Event sourcing
cqrs:
  version: 1

# ElasticSearch
jest:
  elasticsearch:
    host: 192.168.1.12
    port: 9200
    index: library
    mapping: mapping/CategoryMapping.json