spring:
  datasource:
    testWhileIdle: true
    validationQuery: SELECT 1
  cache:
    type: NONE
# JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
# ElasticSearch
  elasticsearch:
    jest:
      uris: http://192.168.1.12:8084
      index: library:mapping/CategoryMapping.json,comments:mapping/CommentsMapping.json,favorites:mapping/FavoritesMapping.json,scores:mapping/ScoresMapping.json

# Eureka
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://127.0.0.1:8099/eureka}
    fetch-registry: true
  instance:
    preferIpAddress: true

# Logging
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
  file: /logs/app.log

# DB Pool
bonecp:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://192.168.1.12:8083/sharingcraftsmanlibrary
  username: scpostgres
  password: scdbp4ss!!
  idleMaxAgeInMinutes: 240
  idleConnectionTestPeriodInMinutes: 60
  maxConnectionsPerPartition: 10
  minConnectionsPerPartition: 1
  partitionCount: 2
  acquireIncrement: 5
  statementsCacheSize: 100

# CQRS Event sourcing
cqrs:
  version: 1