spring:
  datasource:
    testWhileIdle: true
    validationQuery: SELECT 1
  cache:
    type: NONE
# JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
# Upload
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

# Eureka
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://127.0.0.1:8099/eureka}
    fetch-registry: true
  instance:
    preferIpAddress: true
    hostname: 127.0.0.1

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
  file: /logs/app.log

bonecp:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://192.168.1.12:5432/sharincraftsmanlibrary
  username: docker
  password: docker
  idleMaxAgeInMinutes: 240
  idleConnectionTestPeriodInMinutes: 60
  maxConnectionsPerPartition: 10
  minConnectionsPerPartition: 1
  partitionCount: 2
  acquireIncrement: 5
  statementsCacheSize: 100