# Spring
spring:
  datasource:
    testWhileIdle: true
    validationQuery: SELECT 1
    initialize: false
  cache:
    type: NONE
# JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect

# Eureka
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:<EUREKA_PATH>}
  instance:
    preferIpAddress: true

# Logging
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
  file: ${LOGS_PATH}/knowledge-library.log

bonecp:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
  username: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  idleMaxAgeInMinutes: 240
  idleConnectionTestPeriodInMinutes: 60
  maxConnectionsPerPartition: 10
  minConnectionsPerPartition: 1
  partitionCount: 2
  acquireIncrement: 5
  statementsCacheSize: 100

cqrs:
  version: 1